version: '3.1'
name: fovea

services:
  frontend:
    build: .
    container_name: frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env.docker